CREATE TABLE IF NOT EXISTS chat
(
    ID         BIGINT      PRIMARY KEY
);


CREATE TABLE IF NOT EXISTS link
(
    ID           BIGSERIAL PRIMARY KEY,
    URL          varchar(255) NOT NULL,
    Last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    Checked_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    Created_at   TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP,
    Answer_count INT
);

CREATE TABLE IF NOT EXISTS chat_link
(
    Chat_id BIGINT REFERENCES CHAT(ID) ON DELETE CASCADE,
    Link_id BIGINT REFERENCES LINK(ID) ON DELETE CASCADE,
    PRIMARY KEY(Chat_id, Link_id)
);

CREATE TABLE IF NOT EXISTS questions(
    ID BIGSERIAL PRIMARY KEY,
    Answer_count INT,
    Link_id BIGINT,
    FOREIGN KEY (Link_id) REFERENCES LINK(ID) ON DELETE CASCADE
);
