/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.records;

import edu.java.domain.jooq.tables.Questions;

import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.18.9"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class QuestionsRecord extends UpdatableRecordImpl<QuestionsRecord> implements Record3<Long, Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>QUESTIONS.ID</code>.
     */
    public void setId(@Nullable Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>QUESTIONS.ID</code>.
     */
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>QUESTIONS.ANSWER_COUNT</code>.
     */
    public void setAnswerCount(@Nullable Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>QUESTIONS.ANSWER_COUNT</code>.
     */
    @Nullable
    public Integer getAnswerCount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>QUESTIONS.LINK_ID</code>.
     */
    public void setLinkId(@Nullable Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>QUESTIONS.LINK_ID</code>.
     */
    @Nullable
    public Long getLinkId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Integer, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Integer, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return Questions.QUESTIONS.ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return Questions.QUESTIONS.ANSWER_COUNT;
    }

    @Override
    @NotNull
    public Field<Long> field3() {
        return Questions.QUESTIONS.LINK_ID;
    }

    @Override
    @Nullable
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Integer component2() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Long component3() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Integer value2() {
        return getAnswerCount();
    }

    @Override
    @Nullable
    public Long value3() {
        return getLinkId();
    }

    @Override
    @NotNull
    public QuestionsRecord value1(@Nullable Long value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionsRecord value2(@Nullable Integer value) {
        setAnswerCount(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionsRecord value3(@Nullable Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public QuestionsRecord values(@Nullable Long value1, @Nullable Integer value2, @Nullable Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuestionsRecord
     */
    public QuestionsRecord() {
        super(Questions.QUESTIONS);
    }

    /**
     * Create a detached, initialised QuestionsRecord
     */
    @ConstructorProperties({"id", "answerCount", "linkId"})
    public QuestionsRecord(@Nullable Long id, @Nullable Integer answerCount, @Nullable Long linkId) {
        super(Questions.QUESTIONS);

        setId(id);
        setAnswerCount(answerCount);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised QuestionsRecord
     */
    public QuestionsRecord(edu.java.domain.jooq.tables.pojos.Questions value) {
        super(Questions.QUESTIONS);

        if (value != null) {
            setId(value.getId());
            setAnswerCount(value.getAnswerCount());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
